baseURL: "/"
contentDir: "content"
publishDir: "public"

canonifyurls: true
relativeURLS: false

theme: 'PaperMod'
title: "Matt's Medidative Musings"
languageCode: "en-us"
summaryLength: 42
SectionPagesMenu: "main"
googleAnalytics: ""
enableRobotsTXT: true


copyright: "The contents of this website are copyright © Matt Maguire"

sitemap:
  changefreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"

author:
  name: "Matt Maguire"

params:
  description: "This blog contains a miscellany of musings on various topics that happen to pique my interest."
  defaultTheme: auto
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowFullTextinRSS: true
  ShowCodeCopyButtons: true
  disableScrollToTop: true
  showtoc: true
  tocopen: false
  hideFooter: true
  showFooterCredits: true
  math: true
  useIcon: true
  homeInfoParams:
    enabled: true
    Title: "Matt's Meanderings"
    Content: "This blog contains a miscellany of musings on various topics that happen to pique my interest."
  profileMode:
    enabled: false
    title: "Matt Maguire"
    subtitle: "So much to learn, so little time"
  socialIcons:
    - name: 'Mastodon'
      url: 'https://mathstodon.xyz/@MattEducator'
    - name: 'Github'
      url: 'https://github.com/matt-maguire'
    - name: 'LinkedIn'
      url: 'https://linkedin.com/in/maguire-matt/'

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: nord
  goldmark:
    renderer:
      unsafe: true

OutputFormats:
  RSS:
    mediatype: "application/rss+xml"
    baseName: "feed"
